spring:
  application:
    name: client-service
  cloud:
    kubernetes:
      discovery:
        all-namespaces: false
        primary-port-name: http

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  level:
    com.rana: INFO
    org.springframework.cloud.kubernetes: INFO
    org.springframework.web: INFO
